'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'ja';
type TranslationMap = Record<string, string>;

type LanguageContextType = {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: string) => string;
};

const translations: Record<Language, TranslationMap> = {
    en: {
        dashboard: 'Dashboard',
        horses: 'Horses',
        clients: 'Clients',
        settings: 'Settings',
        billing: 'Billing',
        help: 'Help',
        signOut: 'Sign out',
        home: 'Home',
        login: 'Log in',
        startFreeTrial: 'Start free trial',
        contactSales: 'Contact sales',
        lpEyebrow: 'Owner Reporting Platform',
        lpHeadline: 'Monthly reporting for racehorse farms, shaped by real operational feedback',
        lpSubheadline: 'Shinba Report was shaped through repeated feedback from active farms, helping teams organize horse updates, photos, and comments into clear monthly reports for owners and related parties.',
        lpHeroSecondary: 'Built around what farms actually need in daily work',
        lpNoCardNote: 'Trial and payment details are shown at checkout.',
        lpAudienceTitle: 'Built for',
        lpAudienceBody: 'Built for farms, trainers, and consignors who report to owners and bloodstock clients on a recurring basis.',
        lpPricingTitle: 'Pricing',
        lpPricingBody: 'Basic JPY 5,980 / Pro JPY 14,800 / Premium JPY 34,800.',
        lpFeature1Title: 'Bilingual reporting',
        lpFeature1Body: 'Create owner reports in Japanese and English from one place, with room to add more languages later.',
        lpFeature2Title: 'Client-ready presentation',
        lpFeature2Body: 'Put horse updates, photos, and comments into a report that is ready to send.',
        lpFeature3Title: 'Operational consistency',
        lpFeature3Body: 'Keep report style, wording, and presentation consistent across the farm.',
        lpTutorialTitle: 'How it works',
        lpTutorialStep1: 'Set your stable profile, language, and branding.',
        lpTutorialStep2: 'Register horses, clients, and monthly updates in one workspace.',
        lpTutorialStep3: 'Generate reports, export them as PDFs, and deliver them to owners.',
        lpLanguageSupportLabel: 'Language support',
        lpLanguageSupportBody: 'The screen currently supports Japanese and English. Reports can be expanded to other major languages over time.',
        lpPlannedTitle: 'Planned extensions',
        lpPlannedBody: 'Weight tracking is available now. Veterinary summaries, reproductive workflows, and richer structured health records are planned as future modules.',
        lpAllLanguagesTitle: 'Can Shinba support more languages?',
        lpAllLanguagesBody: 'Yes. The current version supports Japanese and English on screen, and reports can be expanded to other major languages in future updates.',
        legalTerms: 'Terms of Service',
        legalPrivacy: 'Privacy Policy',
        legalRefund: 'Refund & Cancellation',
        contact: 'Contact',
        loginTitle: 'Sign in to Shinba Report',
        loginSubtitle: 'Owner reporting for modern racehorse operations.',
        loginEmail: 'Email',
        loginPassword: 'Password',
        loginProcessing: 'Processing...',
        loginSignIn: 'Sign in',
        loginSignUp: 'Create account',
        loginToggleSignIn: 'Already have an account?',
        loginToggleSignUp: 'First time here?',
        loginConfirmation: 'Confirmation email sent. Please check your inbox.',
        backToHome: 'Back to home',
        dashboardWelcomeTitle: 'Racehorse reporting, organized around real operation.',
        dashboardWelcomeBody: 'Manage horses, clients, monthly reports, and style memory from one workspace built for racehorse reporting rather than generic AI writing.',
        subscriptionNoticeTitle: 'How plans work',
        subscriptionNoticeBody: 'Basic covers core generation. Pro adds audience-aware writing backed by Shinba Report shared knowledge. Premium adds learning from your own edit diffs on top of that shared base.',
        totalReports: 'Total reports',
        activeHorses: 'Active horses',
        totalClients: 'Clients',
        recentReports: 'Recent reports',
        horseName: 'Horse',
        reportTitle: 'Report title',
        date: 'Date',
        status: 'Status',
        actions: 'Actions',
        noReports: 'No recent reports found.',
        newReport: 'New report',
        status_Draft: 'Draft',
        status_Training: 'Training',
        status_Resting: 'Resting',
        status_Spelling: 'Spelling',
        deleteReport: 'Delete report',
        confirmDeleteReport: 'Delete this report?',
        deleteSuccess: 'Report deleted.',
        deleteError: 'Failed to delete report: ',
        billingTitle: 'Billing',
        billingSubtitle: 'Choose the plan that fits your reporting workflow. Start with a trial, then manage your subscription from the Stripe customer portal.',
        billingCurrentPlan: 'Current plan',
        billingPlanName: 'Shinba Report',
        billingStatus: 'Status',
        billingTrialEnds: 'Trial ends',
        billingPeriodEnds: 'Current period ends',
        billingTrialBadge: '14-day trial',
        billingCurrentPlanBadge: 'Current',
        billingHint1: 'One subscription per user.',
        billingHint2: 'Checkout opens in Stripe after you start a subscription.',
        billingHint3: 'Webhook updates plan status in Supabase after payment events arrive.',
        billingLoading: 'Loading billing status...',
        billingLoadError: 'Failed to load billing status.',
        billingCheckoutSuccess: 'Checkout completed. Subscription status will update after webhook processing.',
        billingCheckoutCancelled: 'Checkout was cancelled.',
        billingPlanChanged: 'Your subscription plan was updated.',
        billingNeedEmail: 'A signed-in email address is required.',
        billingUpgrade: 'Upgrade',
        billingUpgradeSelected: 'Start checkout for selected plan',
        billingChangeSelected: 'Change to selected plan',
        billingAlreadyOnPlan: 'You are already on this plan.',
        billingOpeningCheckout: 'Opening checkout...',
        billingOpenPortal: 'Open customer portal',
        billingPlan_basic: 'Basic',
        billingPlan_pro: 'Pro',
        billingPlan_premium: 'Premium',
        billingPrice_basic: 'JPY 5,980 / month',
        billingPrice_pro: 'JPY 14,800 / month',
        billingPrice_premium: 'JPY 34,800 / month',
        billingNote_basic: 'Start with core report generation and saving.',
        billingNote_pro: 'Uses Shinba Report shared knowledge for smarter reporting.',
        billingNote_premium: 'Adds personal learning on top of shared knowledge.',
        billingFeature_basic_1: 'Core report generation',
        billingFeature_basic_2: 'Basic translation',
        billingFeature_basic_3: 'Report saving',
        billingFeature_pro_1: 'Audience-aware writing',
        billingFeature_pro_2: 'Past report retrieval',
        billingFeature_pro_3: 'Shared knowledge-base guidance',
        billingFeature_pro_4: 'Field terminology and reporting patterns',
        billingFeature_premium_1: 'Learning from edit diffs',
        billingFeature_premium_2: 'Personal style optimization',
        billingFeature_premium_3: 'Client and owner adaptation',
        billingFeature_premium_4: 'Future team-wide rules',
        settingsTitle: 'Settings',
        settingsDesc: 'Manage workspace access, branding, and language preferences.',
        userManagement: 'User management',
        userManagementDesc: 'Control which users are allowed to access this workspace.',
        addNewEmail: 'Add new email',
        addUser: 'Add user',
        adding: 'Adding...',
        allowedUsers: 'Allowed users',
        loadingUsers: 'Loading users...',
        noUsersFound: 'No users found.',
        adminRole: 'Admin',
        removeAccess: 'Remove access',
        confirmRemoveUser: 'Remove access for {email}?',
        userRemoved: 'User removed.',
        errorDeleting: 'Failed to remove user: ',
        brandingTitle: 'Workspace branding',
        brandingDesc: 'Customize the farm name, colors, and preferred interface language for this account.',
        farmName: 'Farm name',
        farmNamePlaceholder: 'Blue Ridge Farm',
        primaryColor: 'Primary color',
        accentColor: 'Accent color',
        preferredLanguage: 'Preferred language',
        logoConcept: 'Logo concept',
        customLogo: 'Custom logo',
        customLogoDesc: 'Upload your own logo for the dashboard and report header.',
        uploadLogo: 'Upload logo',
        removeLogo: 'Remove logo',
        logoUploadError: 'Failed to upload logo.',
        logoSavedHint: 'The uploaded logo will appear after you save branding.',
        conceptNature: 'Natural harmony',
        conceptMonogram: 'Equine monogram',
        themePreset: 'Theme preset',
        presetForest: 'Forest classic',
        presetForestDesc: 'Deep green and gold for a premium stable look.',
        presetInk: 'Ink ledger',
        presetInkDesc: 'Cool blue and brass for a sharper editorial feel.',
        presetSand: 'Sand field',
        presetSandDesc: 'Warm earth tones for a softer rural presentation.',
        presetCedar: 'Cedar reserve',
        presetCedarDesc: 'Deep burgundy and sand for a formal bloodstock look.',
        presetHarbor: 'Harbor mist',
        presetHarborDesc: 'Muted teal and pale mineral tones for a calm modern style.',
        presetMidnight: 'Midnight tack',
        presetMidnightDesc: 'Dark charcoal and amber for strong contrast and premium weight.',
        presetAlpine: 'Alpine meadow',
        presetAlpineDesc: 'Fresh alpine green and pale stone for a brighter field-forward tone.',
        presetOxford: 'Oxford blue',
        presetOxfordDesc: 'A clear navy and powder mineral accent for a refined formal finish.',
        presetTerracotta: 'Terracotta yard',
        presetTerracottaDesc: 'Burnt clay and warm amber for a sunlit stable character.',
        presetOlive: 'Olive paddock',
        presetOliveDesc: 'Muted olive and dry grass tones for a grounded rural palette.',
        saveBranding: 'Save branding',
        saving: 'Saving...',
        brandingSaved: 'Branding saved.',
        brandingSaveError: 'Failed to save branding.',
        sellerLabel: 'Seller',
        serviceLabel: 'Service',
        contactLabel: 'Contact',
        lpFreeTrialLabel: 'Free trial',
        lpLanguagesCardLabel: 'Languages',
        lpFeaturesCardLabel: 'Features',
        lpTrialLength: '14 days',
        lpLanguagesCardBody: 'Japanese and English are supported now, with expansion to major global languages in planned phases.',
        lpFeaturesCardBody: 'Monthly report writing support, horse record management, PDF export, and farm branding settings.',
        lpFeaturesSectionTitle: 'Why Shinba Report',
        lpFeaturesSectionSub: 'Built for the daily rhythm of the farm',
        lpTrustTitle: 'Built from real reporting work in the field',
        lpTrustBody: 'This is not a generic report tool. Shinba Report was shaped through direct feedback from active farms and built around the monthly reporting work they actually need to do.',
        lpTrustPoint1: 'Improved through repeated feedback from active farms',
        lpTrustPoint2: 'Built around real monthly reporting workflows',
        lpTrustPoint3: 'Designed to be practical in day-to-day farm operations',
        lpFeatureCard1Title: 'Report Writing Support',
        lpFeatureCard2Title: 'Horse Records',
        lpFeatureCard2Sub: 'Weight records and organized horse data',
        lpFeatureCard3Title: 'Farm Branding',
        lpHowSectionTitle: 'Three steps to start',
        lpCtaTitle: '14 days, free.',
        lpCtaSub: 'Start with a 14-day trial. Billing details are shown at checkout.',
        footerSellerLine: 'Seller: Little Mouse Bloodstock · Service: Shinba Report · Basic JPY 5,980 / Pro JPY 14,800 / Premium JPY 34,800',
        legalCommercial: 'Commercial Disclosure',
        monogramDesc: 'Teal and gold monogram for premium owner reports.',
        natureDesc: 'Natural palette for growth, field work, and monthly updates.',
        helpTitle: 'Guides & rollout',
        helpSubtitle: 'How to introduce Shinba Report into actual monthly reporting work.',
        helpStep1Title: '1. Set up stable context',
        helpStep1Body: 'Register branding, language, and workspace basics so reports start from the right stable identity.',
        helpStep2Title: '2. Organize horses and recipients',
        helpStep2Body: 'Keep horse records and client records ready before monthly updates are generated.',
        helpStep3Title: '3. Generate, edit, and save',
        helpStep3Body: 'Generate reports, fix only the lines that need adjustment, and save the final version back into the workflow.',
        helpStep4Title: '4. Let the writing improve over time',
        helpStep4Body: 'Pro benefits from shared knowledge across the service. On Premium, your own edit diffs become personal learning signals on top of that shared base.',
        helpFeatureTitle: 'What Shinba includes now',
        helpFeature1: 'Horse and client management',
        helpFeature2: 'Audience-aware report generation',
        helpFeature3: 'Output modes for Japanese only, English only, or bilingual reports',
        helpFeature4: 'Billing, customer portal, and plan-based access',
        helpRecommendedTitle: 'What is becoming the differentiation core',
        helpRecommended1: 'Racehorse field terminology and clinical precision',
        helpRecommended2: 'Knowledge-guided generation from past reports and rules',
        helpRecommended3: 'Shared knowledge that keeps improving across the service',
        helpRecommended4: 'Client and owner specific personalization over time',
        helpRagTitle: 'Why the memory layer matters',
        helpRagBody: 'Shinba is moving beyond one-off generation. The goal is a reporting loop where shared racehorse knowledge improves the common base, while Premium users also get personal rewrite preferences and audience-aware style returned to future generation.',
        mobileMenu: 'Menu',
        billingGuardRemovedTitle: 'Why Billing no longer blocks every page',
        billingGuardRemovedBody: 'Teams can now inspect the product before committing. Billing only controls subscription start and plan management rather than preventing all access up front.',
        loading: 'Loading...',
        view: 'View',
        deleteConfirm: 'Are you sure you want to delete',
        addClient: 'Add Client',
        addHorse: 'Add Horse',
        newClient: 'New Client',
        createClient: 'Create Client',
        editClient: 'Edit Client',
        clientBasicInfo: 'Basic Information',
        clientName: 'Client Name / Company Name',
        representativeName: 'Representative Name',
        contactInfo: 'Contact Information',
        email: 'Email',
        phone: 'Phone',
        address: 'Address',
        zipCode: 'Zip Code',
        prefecture: 'Prefecture',
        city: 'City',
        street: 'Street / Building',
        notes: 'Notes',
        cancel: 'Cancel',
        saveChanges: 'Save Changes',
        owner: 'Owner',
        noOwner: 'No Owner',
        ownerTransfer: 'Owner (Transfer)',
        searchOwnerPlaceholder: 'Search or create new owner...',
        newOwnerWillBeCreated: 'New owner will be created:',
        horseNameJp: 'Horse Name (JP)',
        horseNameEn: 'Horse Name (EN)',
        sire: 'Sire',
        sireJp: 'Sire (JP)',
        sireEn: 'Sire (EN)',
        dam: 'Dam',
        damJp: 'Dam (JP)',
        damEn: 'Dam (EN)',
        createReportBtn: 'Create Monthly Report',
        editProfile: 'Edit Profile',
        save: 'Save',
        basicInfo: 'Basic Info',
        reportDate: 'Report Date',
        photo: 'Photo',
        selectImage: 'Select Image',
        uploadNewPhoto: 'Upload New Photo',
        statusStats: 'Status & Stats',
        training: 'Training',
        condition: 'Condition',
        currentWeight: 'Current Weight',
        weight: 'Weight',
        weightHistory: 'Weight History',
        aiComments: 'AI Comments',
        englishComment: 'English Comment',
        japaneseTranslation: 'Japanese Translation',
        trainersComment: 'Comment',
        monthlyReport: 'Monthly Report',
        horseStatusLabel: 'Status',
        horseStatusActive: 'Active',
        horseStatusResting: 'Resting',
        horseStatusInjured: 'Injured',
        horseStatusRetired: 'Departed',
        horseStatusSold: 'Sold',
        horseStatusOther: 'Other',
        birthDate: 'Birth Date',
        age: 'Age',
        sex: 'Sex',
        sexAge: 'Sex / Age',
        reportCount: 'Reports',
        lastUpdate: 'Last Update',
        consentTitle: 'Consent for anonymized service-improvement data',
        consentBody: 'We may later use fully anonymized service data for product improvement and statistical analysis. This anonymized data will exclude direct identifiers such as names, direct contact details, and individual horse names. Please choose whether you allow this use.',
        consentAccept: 'I consent',
        consentDecline: 'Do not use my data',
        consentDeclineNote: 'You can change this decision later in Settings.',
        consentSaveError: 'Failed to save your consent setting.',
        consentAcceptedMessage: 'Consent saved. Anonymized use is allowed.',
        consentDeclinedMessage: 'Preference saved. Anonymized use is not allowed.',
        consentSettingsTitle: 'Anonymized data consent',
        consentSettingsDesc: 'Choose whether anonymized service data may be used later for product improvement and statistical analysis.',
        consentStatusPending: 'Current status: no decision yet.',
        consentStatusAccepted: 'Current status: consent granted.',
        consentStatusDeclined: 'Current status: consent declined.',
        backToHorses: 'Back to horses',
        reportHistory: 'Report history',
        noReportsYet: 'No reports yet. Create one first.',
        untitledReport: 'Untitled report',
        loadingWorkspace: 'Loading workspace...',
        loadingReport: 'Loading report...',
        selectHorse: 'Select a horse',
        selectHorseBody: 'Please select a horse to create a report for.',
        reportBuilder: 'Report Builder',
        newReportLabel: 'New report',
        reportEditorLabel: 'Report editor',
        savedAt: 'Saved',
        saveReport: 'Save report',
        generating: 'Generating...',
        generateBilingual: 'Generate EN & JP',
        aiWriter: 'AI Writer',
        editPhoto: 'Edit photo',
        applyCrop: 'Apply',
        selectCondition: 'Select condition...',
        addHistoryRow: 'Add history row',
        enterEnglishComment: 'Enter comment in English...',
        enterJapaneseComment: 'Enter comment in Japanese...',
        noPhotoSelected: 'No photo selected',
        monthlyReports: 'Monthly reports',
        noActiveWorkspace: 'No active workspace selected.',
        noHorseSelected: 'No horse selected.',
        imageUploadFailed: 'Failed to upload image.',
        checkStoragePolicies: 'Please check Supabase Storage policies.',
        errorSavingReport: 'Error saving report: ',
        saveReportFirst: 'Please save the report first.',
        errorUpdatingClient: 'Error updating client: ',
    },
    ja: {
        dashboard: 'ダッシュボード',
        horses: '馬一覧',
        clients: 'クライアント一覧',
        settings: '設定',
        billing: 'Billing',
        help: 'ガイド',
        signOut: 'サインアウト',
        home: 'ホーム',
        login: 'ログイン',
        startFreeTrial: '無料トライアルを開始',
        contactSales: 'お問い合わせ',
        lpEyebrow: 'オーナーレポートプラットフォーム',
        lpHeadline: '競走馬牧場運営のための月次レポートを、より上質に、より効率的に。',
        lpSubheadline: 'Shinba Report は、現役牧場から何度も意見をもらいながら形にしてきたサービスです。馬の近況、写真、コメントを整理し、馬主や関係者へ届ける月次レポートをわかりやすく整えられます。',
        lpHeroSecondary: '現場で本当に必要とされる流れに合わせた月次レポート設計',
        lpNoCardNote: 'トライアルとお支払い条件は申込画面で確認できます。',
        lpAudienceTitle: '対象ユーザー',
        lpAudienceBody: '牧場、調教師、コンサイナーなど、馬主や血統・販売クライアントへ継続的に近況報告を行うチームに適しています。',
        lpPricingTitle: '料金',
        lpPricingBody: '月額29ドル、14日間の無料トライアル付きです。',
        lpFeature1Title: '日英対応のレポート作成',
        lpFeature1Body: '日本語と英語のレポートを1か所でまとめて作れるため、相手に合わせた報告がしやすくなります。',
        lpFeature2Title: 'そのまま提出できる品質',
        lpFeature2Body: '馬の近況、写真、体重、コメントをまとめて、そのまま送れる形のレポートにできます。',
        lpFeature3Title: '運営全体の標準化',
        lpFeature3Body: '馬情報やレポートの見せ方をまとめて整え、毎月の報告のばらつきを減らします。',
        lpTutorialTitle: '使い方',
        lpTutorialStep1: 'まず、牧場名・ブランドカラー・表示言語を設定します。',
        lpTutorialStep2: '次に、馬情報とクライアント情報を登録し、月次の更新内容を整理します。',
        lpTutorialStep3: '最後に、レポートを生成し、PDFとして出力して馬主へ共有します。',
        lpLanguageSupportLabel: '言語対応',
        lpLanguageSupportBody: '画面は現在、日本語と英語に対応しています。今後は必要に応じて他の主要言語にも広げていく予定です。',
        lpPlannedTitle: '今後の拡張予定',
        lpPlannedBody: '体重管理は現在対応済みです。獣医サマリー、繁殖ワークフロー、より詳細なヘルスレコードは今後の追加モジュールとして展開予定です。',
        lpAllLanguagesTitle: '世界の主要言語対応は可能か',
        lpAllLanguagesBody: '可能です。現在は日本語と英語に対応しており、今後は必要に応じて他の主要言語にも広げていく想定です。',
        legalTerms: '利用規約',
        legalPrivacy: 'プライバシーポリシー',
        legalRefund: '返金・解約ポリシー',
        contact: 'お問い合わせ',
        loginTitle: 'Shinba Report にログイン',
        loginSubtitle: '競走馬運営向けのオーナーレポート管理システム',
        loginEmail: 'メールアドレス',
        loginPassword: 'パスワード',
        loginProcessing: '処理中...',
        loginSignIn: 'ログイン',
        loginSignUp: 'アカウント作成',
        loginToggleSignIn: 'すでにアカウントをお持ちですか？',
        loginToggleSignUp: '初めて利用しますか？',
        loginConfirmation: '確認メールを送信しました。受信箱を確認してください。',
        backToHome: 'トップへ戻る',
        dashboardWelcomeTitle: '月次レポート業務を、1つの画面で進めやすく。',
        dashboardWelcomeBody: '馬情報、送付先、レポート作成をまとめて管理できます。毎月の報告をためらわずに回せることを重視した作りです。',
        subscriptionNoticeTitle: '',
        subscriptionNoticeBody: '',
        totalReports: 'レポート数',
        activeHorses: '管理馬数',
        totalClients: 'クライアント数',
        recentReports: '最近のレポート',
        horseName: '馬名',
        reportTitle: 'タイトル',
        date: '日付',
        status: '状態',
        actions: '操作',
        noReports: '最近のレポートはありません。',
        newReport: '新規レポート',
        status_Draft: '下書き',
        status_Training: '調教中',
        status_Resting: '休養中',
        status_Spelling: '放牧中',
        deleteReport: 'レポート削除',
        confirmDeleteReport: 'このレポートを削除しますか？',
        deleteSuccess: 'レポートを削除しました。',
        deleteError: '削除に失敗しました: ',
        billingTitle: 'ご利用プラン',
        billingSubtitle: '業務に合ったプランを選べます。申込みや変更はこの画面から進められます。',
        billingCurrentPlan: '現在のプラン',
        billingPlanName: 'Shinba Report',
        billingStatus: 'ステータス',
        billingTrialEnds: 'トライアル終了日',
        billingPeriodEnds: '次回更新日',
        billingTrialBadge: '14日間無料',
        billingCurrentPlanBadge: '契約中',
        billingHint1: '契約はユーザー単位です。',
        billingHint2: '申込み時に決済画面へ移動します。',
        billingHint3: '決済完了後、この画面の契約状態が更新されます。',
        billingLoading: '課金状態を読み込み中です...',
        billingLoadError: '課金状態の読み込みに失敗しました。',
        billingCheckoutSuccess: 'お申込みが完了しました。しばらくすると契約状態が更新されます。',
        billingCheckoutCancelled: 'お申込みはキャンセルされました。',
        billingPlanChanged: 'サブスクリプションのプランを更新しました。',
        billingNeedEmail: 'ログイン中のメールアドレスが必要です。',
        billingUpgrade: 'アップグレード',
        billingUpgradeSelected: '選択したプランで申込む',
        billingChangeSelected: '選択したプランへ変更する',
        billingAlreadyOnPlan: '現在このプランを利用中です。',
        billingOpeningCheckout: '決済画面を開いています...',
        billingOpenPortal: '契約管理画面を開く',
        billingPlan_basic: 'Basic',
        billingPlan_pro: 'Pro',
        billingPlan_premium: 'Premium',
        billingPrice_basic: '月額5,980円',
        billingPrice_pro: '月額14,800円',
        billingPrice_premium: '月額34,800円',
        billingNote_basic: 'まずはレポート作成を始めたい方向けです。',
        billingNote_pro: '最初から使いやすい下書きを出したい方向けです。',
        billingNote_premium: '自分の直し方まで反映させたい方向けです。',
        billingFeature_basic_1: '基本レポート生成',
        billingFeature_basic_2: '基本翻訳',
        billingFeature_basic_3: 'レポート保存',
        billingFeature_pro_1: '相手に合わせた文面調整',
        billingFeature_pro_2: '過去レポートを参考に生成',
        billingFeature_pro_3: '共有ルールを反映',
        billingFeature_pro_4: '現場でよく使う表現に強い',
        billingFeature_premium_1: '保存時の手直しを記録',
        billingFeature_premium_2: '自分の言い回しに近づく',
        billingFeature_premium_3: '送り先ごとの調整を蓄積',
        billingFeature_premium_4: '将来的なチーム共有ルール',
        settingsTitle: '設定',
        settingsDesc: 'ワークスペースのアクセス権、ブランド設定、表示言語を管理します。',
        userManagement: 'ユーザー管理',
        userManagementDesc: 'このワークスペースにアクセスできるユーザーを管理します。',
        addNewEmail: '追加するメール',
        addUser: 'ユーザー追加',
        adding: '追加中...',
        allowedUsers: '許可済みユーザー',
        loadingUsers: 'ユーザーを読み込み中...',
        noUsersFound: 'ユーザーが見つかりません。',
        adminRole: '管理者',
        removeAccess: 'アクセスを削除',
        confirmRemoveUser: '{email} のアクセス権を削除しますか？',
        userRemoved: 'ユーザーを削除しました。',
        errorDeleting: '削除に失敗しました: ',
        brandingTitle: 'ワークスペースブランド',
        brandingDesc: '牧場名、色、表示言語をアカウントごとに設定できます。',
        farmName: '牧場名',
        farmNamePlaceholder: 'Blue Ridge Farm',
        primaryColor: 'メインカラー',
        accentColor: 'アクセントカラー',
        preferredLanguage: '優先言語',
        logoConcept: 'ロゴコンセプト',
        customLogo: 'カスタムロゴ',
        customLogoDesc: 'ダッシュボードとレポート上部に表示する自社ロゴをアップロードできます。',
        uploadLogo: 'ロゴをアップロード',
        removeLogo: 'ロゴを削除',
        logoUploadError: 'ロゴのアップロードに失敗しました。',
        logoSavedHint: '保存するとアップロードしたロゴが反映されます。',
        conceptNature: 'ナチュラルハーモニー',
        conceptMonogram: 'モノグラム',
        themePreset: 'テーマプリセット',
        presetForest: 'フォレストクラシック',
        presetForestDesc: '深い緑とゴールドで、落ち着いた上質感を出します。',
        presetInk: 'インクレジャー',
        presetInkDesc: '青みのある濃色と真鍮色で、シャープな印象に整えます。',
        presetSand: 'サンドフィールド',
        presetSandDesc: '暖かいアースカラーで、やわらかな牧場らしさを出します。',
        presetCedar: 'シダ―リザーブ',
        presetCedarDesc: '深い赤褐色と砂色で、上品な血統系の印象に整えます。',
        presetHarbor: 'ハーバーミスト',
        presetHarborDesc: '落ち着いた青緑と淡い無機色で、静かなモダン感を出します。',
        presetMidnight: 'ミッドナイトタック',
        presetMidnightDesc: '濃いチャコールと琥珀色で、強いコントラストと重厚感を出します。',
        presetAlpine: 'アルパインメドウ',
        presetAlpineDesc: '明るい高原グリーンと淡い石色で、抜け感のある牧場トーンに整えます。',
        presetOxford: 'オックスフォードブルー',
        presetOxfordDesc: '澄んだネイビーと淡い鉱物色で、端正で知的な印象に整えます。',
        presetTerracotta: 'テラコッタヤード',
        presetTerracottaDesc: '焼き土色と暖かな琥珀色で、日差しのある厩舎らしさを出します。',
        presetOlive: 'オリーブパドック',
        presetOliveDesc: '渋いオリーブと乾いた草色で、地に足のついた牧場感を出します。',
        saveBranding: 'ブランド設定を保存',
        saving: '保存中...',
        brandingSaved: 'ブランド設定を保存しました。',
        brandingSaveError: 'ブランド設定の保存に失敗しました。',
        sellerLabel: '販売事業者',
        serviceLabel: 'サービス名',
        contactLabel: '連絡先',
        lpFreeTrialLabel: '無料期間',
        lpLanguagesCardLabel: '対応言語',
        lpFeaturesCardLabel: '主な機能',
        lpTrialLength: '14日間',
        lpLanguagesCardBody: '現在は日本語と英語に対応し、主要言語への拡張は段階的に進める想定です。',
        lpFeaturesCardBody: 'レポート文作成の補助、馬情報の管理、PDF出力、牧場名や見た目の設定に対応しています。',
        lpFeaturesSectionTitle: '選ばれる理由',
        lpFeaturesSectionSub: '牧場の現場に寄り添う機能設計',
        lpTrustTitle: '現場の報告実務から生まれた設計',
        lpTrustBody: 'よくある汎用ツールではなく、現役牧場から何度も意見をもらいながら、毎月の報告作業に合わせて形にしてきたサービスです。',
        lpTrustPoint1: '現場の意見を取り入れながら改善',
        lpTrustPoint2: '月次報告の実務に沿った設計',
        lpTrustPoint3: '牧場運営で無理なく使える実用性',
        lpFeatureCard1Title: 'レポート文作成サポート',
        lpFeatureCard2Title: '馬情報の整理',
        lpFeatureCard2Sub: '体重記録と馬の基本情報をまとめて管理',
        lpFeatureCard3Title: '牧場ごとの見た目設定',
        lpHowSectionTitle: '3ステップで始まる',
        lpCtaTitle: '14日間、無料で。',
        lpCtaSub: 'まずは14日間のトライアルから。お支払い条件は申込画面で確認できます。',
        footerSellerLine: '販売事業者: Little Mouse Bloodstock · サービス: Shinba Report · Basic 月額5,980円 / Pro 月額14,800円 / Premium 月額34,800円',
        legalCommercial: '特定商取引法に基づく表記',
        monogramDesc: '上質なオーナーレポート向けの、深緑とゴールドのモノグラムです。',
        natureDesc: '牧場らしい柔らかさを出す、自然な配色のスタイルです。',
        helpTitle: '使い方ガイド',
        helpSubtitle: '最初に押さえておきたい基本の流れをまとめています。',
        helpStep1Title: '1. 馬情報と送付先を登録する',
        helpStep1Body: 'まずは馬の基本情報と、レポートを送る相手を登録します。',
        helpStep2Title: '2. 近況メモを入力する',
        helpStep2Body: '調教、体調、体重など、今月伝えたい内容をまとめます。',
        helpStep3Title: '3. レポートを作って必要なところだけ直す',
        helpStep3Body: '下書きを作ったあと、気になる箇所だけ整えて保存します。',
        helpStep4Title: '4. プランに応じて精度が上がる',
        helpStep4Body: 'Pro では過去レポートや共有ルールを使って、最初から整った下書きが出やすくなります。Premium では、保存前に直した表現も次回から反映されるようになります。',
        helpFeatureTitle: 'できること',
        helpFeature1: '馬・クライアント管理',
        helpFeature2: '送り先に合わせたレポート生成',
        helpFeature3: '日本語のみ・英語のみ・併記の出力モード',
        helpFeature4: 'プラン変更と契約管理',
        helpRecommendedTitle: 'Pro と Premium の違い',
        helpRecommended1: 'Pro は過去レポートや共有ルールを参考に下書きを作る',
        helpRecommended2: 'Pro は現場でよく使う表現や用語に強い',
        helpRecommended3: 'Premium は保存前の手直しを覚える',
        helpRecommended4: 'Premium は回数を重ねるほど自分向けに寄っていく',
        helpRagTitle: 'Shinba Report が目指していること',
        helpRagBody: '毎回ゼロから書くのではなく、過去レポートや共有ルールを活かして下書きを整え、必要な人は自分の直し方まで反映できるようにすることを目指しています。',
        mobileMenu: 'メニュー',
        billingGuardRemovedTitle: 'すべての画面が Billing に飛ばない理由',
        billingGuardRemovedBody: '契約前でもプロダクトを見て判断できるようにしています。課金導線は Billing でのみ扱い、最初からすべてをブロックしない設計にしています。',
        loading: '読み込み中...',
        view: '詳細',
        deleteConfirm: '削除してもよろしいですか',
        addClient: 'クライアント追加',
        addHorse: '馬を追加',
        newClient: '新規クライアント登録',
        createClient: 'クライアント登録',
        editClient: 'クライアント編集',
        clientBasicInfo: '基本情報',
        clientName: 'クライアント名 / 会社名',
        representativeName: '代表者名',
        contactInfo: '連絡先情報',
        email: 'メールアドレス',
        phone: '電話番号',
        address: '住所',
        zipCode: '郵便番号',
        prefecture: '都道府県',
        city: '市区町村',
        street: '番地・建物名',
        notes: '備考',
        cancel: 'キャンセル',
        saveChanges: '変更を保存',
        owner: '馬主',
        noOwner: '所有者なし',
        ownerTransfer: '所有者変更 (譲渡)',
        searchOwnerPlaceholder: '所有者を検索または新規作成...',
        newOwnerWillBeCreated: '新しい所有者が作成されます:',
        horseNameJp: '馬名 (日本語)',
        horseNameEn: '馬名 (英語)',
        sire: '父',
        sireJp: '父 (日本語)',
        sireEn: '父 (英語)',
        dam: '母',
        damJp: '母 (日本語)',
        damEn: '母 (英語)',
        createReportBtn: '月次レポート作成',
        editProfile: 'プロフィール編集',
        save: '保存',
        basicInfo: '基本情報',
        reportDate: 'レポート年月',
        photo: '写真',
        selectImage: '画像を選択',
        uploadNewPhoto: '新しい写真をアップロード',
        statusStats: 'ステータス・統計',
        training: '調教状況',
        condition: '体調',
        currentWeight: '現在の体重',
        weight: '体重',
        weightHistory: '体重推移',
        aiComments: 'AIコメント生成',
        englishComment: '英語コメント',
        japaneseTranslation: '日本語翻訳',
        trainersComment: 'コメント',
        monthlyReport: '月次レポート',
        horseStatusLabel: 'ステータス',
        horseStatusActive: '在厩中',
        horseStatusResting: '休養中',
        horseStatusInjured: '怪我',
        horseStatusRetired: '退厩',
        horseStatusSold: '売却',
        horseStatusOther: 'その他',
        birthDate: '生年月日',
        age: '年齢',
        sex: '性別',
        sexAge: '性別・年齢',
        reportCount: 'レポート数',
        lastUpdate: '最終更新',
        consentTitle: '匿名化データ利用への同意',
        consentBody: '今後、サービス改善や統計分析のために、十分に匿名化したサービス利用データを活用する可能性があります。匿名化データには、氏名、直接の連絡先、個別の馬名などの識別子は含めません。この利用を許可するかどうかを選択してください。',
        consentAccept: '同意する',
        consentDecline: '同意しない',
        consentDeclineNote: 'この設定は後から設定画面で変更できます。',
        consentSaveError: '同意設定の保存に失敗しました。',
        consentAcceptedMessage: '同意設定を保存しました。匿名化データ利用を許可しました。',
        consentDeclinedMessage: '設定を保存しました。匿名化データ利用は許可していません。',
        consentSettingsTitle: '匿名化データ利用設定',
        consentSettingsDesc: '匿名化したサービスデータを、今後のプロダクト改善や統計分析に使ってよいかを設定します。',
        consentStatusPending: '現在の状態: まだ回答していません。',
        consentStatusAccepted: '現在の状態: 同意済みです。',
        consentStatusDeclined: '現在の状態: 不同意です。',
        backToHorses: '馬一覧に戻る',
        reportHistory: 'レポート履歴',
        noReportsYet: 'レポートはまだありません。作成してください。',
        untitledReport: '無題のレポート',
        loadingWorkspace: 'ワークスペースを読み込み中...',
        loadingReport: 'レポートを読み込み中...',
        selectHorse: '馬を選択',
        selectHorseBody: 'レポートを作成する馬を選択してください。',
        reportBuilder: 'レポートビルダー',
        newReportLabel: '新規レポート',
        reportEditorLabel: 'レポート編集',
        savedAt: '保存済み',
        saveReport: 'レポート保存',
        generating: '生成中...',
        generateBilingual: '英日コメント生成',
        aiWriter: 'AI Writer',
        editPhoto: '写真を調整',
        applyCrop: '適用',
        selectCondition: '体調を選択...',
        addHistoryRow: '履歴行を追加',
        enterEnglishComment: '英語コメントを入力...',
        enterJapaneseComment: '日本語コメントを入力...',
        noPhotoSelected: '写真が未設定です',
        monthlyReports: '月次レポート',
        noActiveWorkspace: 'アクティブなワークスペースがありません。',
        noHorseSelected: '馬が選択されていません。',
        imageUploadFailed: '画像アップロードに失敗しました。',
        checkStoragePolicies: 'Supabase Storage のポリシーを確認してください。',
        errorSavingReport: 'レポート保存エラー: ',
        saveReportFirst: '先にレポートを保存してください。',
        errorUpdatingClient: 'クライアント更新エラー: ',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('ja');

    useEffect(() => {
        const saved = window.localStorage.getItem('shinba-language');
        if (saved === 'ja' || saved === 'en') {
            setLanguageState(saved);
            return;
        }

        const nav = window.navigator.language || '';
        if (nav.toLowerCase().startsWith('en')) {
            setLanguageState('en');
        }
    }, []);

    const setLanguage = (nextLanguage: Language) => {
        setLanguageState(nextLanguage);
        window.localStorage.setItem('shinba-language', nextLanguage);
    };

    const value = useMemo(
        () => ({
            language,
            setLanguage,
            t: (key: string) => translations[language][key] || translations.en[key] || key,
        }),
        [language],
    );

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
